Make text input optional to SectionBlock
nicklambourne/slackblocks pull request #23
Opened 2022-11-22 20:52 UTC by palewire

2022-11-22 20:52 UTC, palewire commented
For #22

2022-12-01 12:14 UTC, nicklambourne commented on slackblocks/blocks.py
> +            self.text = text
```suggestion
        if not text or type(text) is Text:
            self.text = text
        else:
            self.text = Text(text)
```

2022-12-01 12:17 UTC, nicklambourne requested changes
Apologies for the delay in getting to this, what do you think about my suggestion for simplifying it a little?

2022-12-01 16:25 UTC, palewire commented on slackblocks/blocks.py
> +            self.text = text
Looks good to me.

2022-12-01 16:25 UTC, palewire commented
Love it.

2022-12-04 11:00 UTC, merged